### ISSUE TITLE
-vo option does not parse (

### ISSUE THREAD

**Issue by CharlesSS07** [eidelen/DicomToMesh#25]
Hi,

Maybe you know what I am doing wrong.
`
~$ ./DicomToMesh/build/dicom2mesh/dicom2mesh -i OrtogOnBlender/ARQUIVOS/ARCADAS/ARCADAS_TOMO/INFERIOR/ -vo (255,0,0,0,0) (255,0,0,60,700) (200,200,200,90,2000)`
`bash: syntax error near unexpected token '('`

Everything works perfectly, including the gui, however, the -v option does not show any meshes, and the -vo errors on the "(" .

I come from the CG field. More specifically, I use Blender3D, which has recently added a features which allows it to read openvdb files. I know that this is DicomToMesh and not DicomToVolume, but I feel like having a -o volume.vdb would totally replace the need for the visualization tools that come with DicomToMesh currently by allowing blender (or any other software that reads vdb) to do all the visualization.

Thanks, and let me know if I just messed up the compiling

**Comment by CharlesSS07** [comment]
Maybe this helps. I took away the `(` and `)` and it runs into a seg fault. But without the `-vo flag`, exits normally.

With -vo (no parens)
```
~$ ./DicomToMesh/build/dicom2mesh/dicom2mesh -i OrtogOnBlender/ARQUIVOS/ARCADAS/ARCADAS_TOMO/INFERIOR/ -vo 255,0,0,0,0 255,0,0,60,700 200,200,200,90,2000

Dicom2Mesh Settings

Input directory: OrtogOnBlender/ARQUIVOS/ARCADAS/ARCADAS_TOMO/INFERIOR/
Output file path: mesh.stl
Surface segmentation: 400
Mesh reduction: disabled
Mesh polygon limitation: disabled
Mesh smoothing: disabled
Mesh centering: disabled
Mesh filtering: disabled
Volume cropping: disabled

Using standard DICOM loader
Read DICOM images located under OrtogOnBlender/ARQUIVOS/ARCADAS/ARCADAS_TOMO/INFERIOR/
2020-06-09 17:15:37.892 (   0.009s) [        B05F3780]vtkDICOMImageReader.cxx:105   WARN| vtkDICOMImageReader (0x55eb2efd6ff0): DICOMParser couldn't parse : OrtogOnBlender/ARQUIVOS/ARCADAS/ARCADAS_TOMO/INFERIOR//ListaArquivos.txt
Progress: done

Create surface mesh with iso value = 400
Progress: done


Required computing time: 2 seconds
2020-06-09 17:15:40.195 (   2.312s) [        B05F3780]vtkInteractorStyleSwitc:37    WARN| vtkInteractorStyleSwitchBase (0x55eb2eff1ff0): Warning: Link to vtkInteractionStyle for default style selection.
2020-06-09 17:15:40.248 (   2.364s) [        B05F3780]vtkRayCastImageDisplayH:20    WARN| Error: no override found for 'vtkRayCastImageDisplayHelper'.
Segmentation fault (core dumped)
```

Without -vo
```
~$ ./DicomToMesh/build/dicom2mesh/dicom2mesh -i OrtogOnBlender/ARQUIVOS/ARCADAS/ARCADAS_TOMO/INFERIOR/

Dicom2Mesh Settings

Input directory: OrtogOnBlender/ARQUIVOS/ARCADAS/ARCADAS_TOMO/INFERIOR/
Output file path: mesh.stl
Surface segmentation: 400
Mesh reduction: disabled
Mesh polygon limitation: disabled
Mesh smoothing: disabled
Mesh centering: disabled
Mesh filtering: disabled
Volume cropping: disabled

Using standard DICOM loader
Read DICOM images located under OrtogOnBlender/ARQUIVOS/ARCADAS/ARCADAS_TOMO/INFERIOR/
2020-06-09 17:16:49.250 (   0.004s) [        3EE80780]vtkDICOMImageReader.cxx:105   WARN| vtkDICOMImageReader (0x55b8ec9e2ff0): DICOMParser couldn't parse : OrtogOnBlender/ARQUIVOS/ARCADAS/ARCADAS_TOMO/INFERIOR//ListaArquivos.txt
Progress: done

Create surface mesh with iso value = 400
Progress: done


Required computing time: 2 seconds
```

**Comment by eidelen** [comment]
Hello,
Please try `-vo "(255,0,0,0,0)" "(255,0,0,60,700)" "(200,200,200,90,2000)"`. Did that work?
It's the first time I hear of somebody using this volume rendering option :) So let's get it working!

**Comment by eidelen** [comment]
About the openvdb export option: I think that would be a nice feature and I will have a look at it. Please note that DicomToMesh was never supposed to be a visualisation tool. Personally I use it just to have a first rough glance on the mesh quality. Therefore, I agree with you to let this job be done by other tools.

**Comment by CharlesSS07** [comment]
Hi Adrian,

Thanks for the reply.

Heres my new output with the quotes
```
~$ ./DicomToMesh/build/dicom2mesh/dicom2mesh -i OrtogOnBlender/ARQUIVOS/ARCADAS/ARCADAS_TOMO/INFERIOR/ -vo "(255,0,0,0,0)" "(255,0,0,60,700)" "(200,200,200,90,2000)"

Dicom2Mesh Settings
-------------------
Input directory: OrtogOnBlender/ARQUIVOS/ARCADAS/ARCADAS_TOMO/INFERIOR/
Output file path: mesh.stl
Surface segmentation: 400
Mesh reduction: disabled
Mesh polygon limitation: disabled
Mesh smoothing: disabled
Mesh centering: disabled
Mesh filtering: disabled
Volume cropping: disabled

Using standard DICOM loader
Read DICOM images located under OrtogOnBlender/ARQUIVOS/ARCADAS/ARCADAS_TOMO/INFERIOR/
2020-06-10 10:39:35.092 (   0.009s) [        F72BB780]vtkDICOMImageReader.cxx:105   WARN| vtkDICOMImageReader (0x5594c2e429a0): DICOMParser couldn't parse : OrtogOnBlender/ARQUIVOS/ARCADAS/ARCADAS_TOMO/INFERIOR//ListaArquivos.txt
Progress: done

Create surface mesh with iso value = 400
Progress: done


Required computing time: 2 seconds
2020-06-10 10:39:37.394 (   2.311s) [        F72BB780]vtkInteractorStyleSwitc:37    WARN| vtkInteractorStyleSwitchBase (0x5594c2e7fc40): Warning: Link to vtkInteractionStyle for default style selection.
2020-06-10 10:39:37.447 (   2.364s) [        F72BB780]vtkRayCastImageDisplayH:20    WARN| Error: no override found for 'vtkRayCastImageDisplayHelper'.
Segmentation fault (core dumped)
```

So `Error: no override found for 'vtkRayCastImageDisplayHelper'`? Could this indicate that I am missing something related to vtk? I built VTK myself for this.

-v also has no output for me:
```
~$ ./DicomToMesh/build/dicom2mesh/dicom2mesh -i OrtogOnBlender/ARQUIVOS/ARCADAS/ARCADAS_TOMO/INFERIOR/ -v

Dicom2Mesh Settings
-------------------
Input directory: OrtogOnBlender/ARQUIVOS/ARCADAS/ARCADAS_TOMO/INFERIOR/
Output file path: mesh.stl
Surface segmentation: 400
Mesh reduction: disabled
Mesh polygon limitation: disabled
Mesh smoothing: disabled
Mesh centering: disabled
Mesh filtering: disabled
Volume cropping: disabled

Using standard DICOM loader
Read DICOM images located under OrtogOnBlender/ARQUIVOS/ARCADAS/ARCADAS_TOMO/INFERIOR/
2020-06-10 10:48:42.400 (   0.004s) [        ADD26780]vtkDICOMImageReader.cxx:105   WARN| vtkDICOMImageReader (0x5574fea49ff0): DICOMParser couldn't parse : OrtogOnBlender/ARQUIVOS/ARCADAS/ARCADAS_TOMO/INFERIOR//ListaArquivos.txt
Progress: done

Create surface mesh with iso value = 400
Progress: done


Required computing time: 2 seconds
2020-06-10 10:48:44.704 (   2.308s) [        ADD26780]vtkInteractorStyleSwitc:37    WARN| vtkInteractorStyleSwitchBase (0x5574fea64ff0): Warning: Link to vtkInteractionStyle for default style selection.
```
There is no gui that pops up after that.

I think that I may have compiled something incorrectly.

**Comment by CharlesSS07** [comment]
It would appear that the program was not finding the `vtkRayCastImageDisplayHelper` and needed to be linked to `vtkRenderingVolumeOpenGL2`

I googled the error I was getting, ` Error: no override found for 'vtkRayCastImageDisplayHelper'.`,
and found that I needed to link to link to `vtkRenderingVolumeOpenGL2`. So I did that and now it works. You can see the changes I made below. I'm not sure if this is just that I compiled wrong or if I accidentally fixed something.

Someone with the same error I mentioned in previous posts:
https://stackoverflow.com/questions/50774656/no-override-found-for-vtkraycastimagedisplayhelper

added this to just before the main loop, Links to vtkRenderingVolumeOpenGL2, and fixed my problem
```
#include "vtkAutoInit.h"
VTK_MODULE_INIT(vtkRenderingVolumeOpenGL2) // VTK was built with vtkRenderingOpenGL2
//VTK_MODULE_INIT(vtkInteractionStyle);
```

If you want, Ill make a branch and push these lines.

**Comment by CharlesSS07** [comment]
Actually just realized that I can't rotate the volume render. However, I can rotate the mesh. This is still a big improvement over my original state, but I might still have an issue.

**Comment by eidelen** [comment]
Good that it worked! What version of VTK are you using? Yes, that would be great if you could make a merge branch with your changes.

**Comment by CharlesSS07** [comment]
I am using VTK verions 9.0.0 from https://github.com/Kitware/VTK

**Comment by eidelen** [comment]
I get the same error when using VTK 9.0.0.

**Comment by CharlesSS07** [comment]
I don't really know my way around github. I made a fork with my changes here : https://github.com/CharlesSS07/DicomToMesh

Its like 2 lines in the main.cpp. But if you tell me how to do this, I'll make a merge branch with the changes.

**Comment by eidelen** [comment]
Hi,
No problem - I can get your commit from your repo. Unfortunately, I just observed another issue with VTK 9.0.0. vtk-dicom, an optional library, does not work as usual when using VTK 9.0.0. The common cmake files are missing. 
I need to fix this first. Then I come back to your merge.
