### ISSUE TITLE
Error on Mac OS X during build: library not found for -lpugixml

### ISSUE THREAD

**Issue by cogitas3d** [eidelen/DicomToMesh#30]
Dear friends,

I upgrade de system to Catalina and rebuild the DicomToMesh-vtk-9-novisual branch. All appear works, but at 100% I receive an error message.

Scanning dependencies of target dicom2meshlib
[ 12%] Building CXX object lib/CMakeFiles/dicom2meshlib.dir/src/dicomFactory.cpp.o
[ 25%] Building CXX object lib/CMakeFiles/dicom2meshlib.dir/src/dicomRoutines.cpp.o
[ 37%] Building CXX object lib/CMakeFiles/dicom2meshlib.dir/src/meshData.cpp.o
[ 50%] Building CXX object lib/CMakeFiles/dicom2meshlib.dir/src/meshRoutines.cpp.o
[ 62%] Linking CXX static library libdicom2meshlib.a
[ 62%] Built target dicom2meshlib
Scanning dependencies of target dicom2mesh
[ 75%] Building CXX object dicom2mesh/CMakeFiles/dicom2mesh.dir/src/main.cpp.o
[ 87%] Building CXX object dicom2mesh/CMakeFiles/dicom2mesh.dir/src/dicom2mesh.cpp.o
[100%] Linking CXX executable dicom2mesh
ld: library not found for -lpugixml
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [dicom2mesh/dicom2mesh] Error 1
make[1]: *** [dicom2mesh/CMakeFiles/dicom2mesh.dir/all] Error 2
make: *** [all] Error 2

Is it possible to solve it?

A big hug!

**Comment by eidelen** [comment]
Hi Cicero,
Sorry for the delay. Unfortunately I am still on Mojave. Did you rerun the cmake command? Sometimes it is even the best to just erase the whole build-folder.

**Comment by eidelen** [comment]
Hi Cicero, I suppose this is closed. Feel free to open again. Best regards, Adrian
