### ISSUE TITLE
Prebuilt binaries / build artifacts?

### ISSUE THREAD

**Issue by sammcj** [eidelen/DicomToMesh#41]
Are prebuilt binaries / build artifacts available for macOS builds somewhere?

QT is quite a pain to build applications with on macOS so it would be great to be able to download a working binary.

**Comment by eidelen** [comment]
Hi, Sorry for the late answer. I do not have any prebuilts on OSX or windows, as packing software isn't fun and is especially difficult on these two systems :) However, I developed dicom2mesh under OSX - using brew, it is almost as straight forward as doing it in Ubuntu.
