### ISSUE TITLE
The process of constructing meshes for soft tissues

### ISSUE THREAD

**Issue by Mint41** [eidelen/DicomToMesh#47]
May I inquire if it is permissible for me to employ this project to construct meshes for various soft organ systems, such as the pulmonary organ?
I utilized DICOM files of the lung 
<img width="379" alt="image" src="https://github.com/eidelen/DicomToMesh/assets/75123918/ffc82a8b-277a-4db2-b9d9-e597dce54dec">

and obtained a mesh representing the rib cage instead of the lung

<img width="264" alt="image" src="https://github.com/eidelen/DicomToMesh/assets/75123918/0908cc83-ccdd-4422-849a-d130be0deb77">

Can I obtained a lung mesh by using this program?

**Comment by eidelen** [comment]
Hi,
Sorry for my late reply. I think there exist much better methods for soft tissue segmentation. Have a look at the opensource tool ITK-SNAP.
