### ISSUE TITLE
Could someone please make a video on how to follow these steps on Mac

### ISSUE THREAD

**Issue by IganoKabamar** [eidelen/DicomToMesh#49]
Thanks in advance for reading this.

Could someone(if they are kind enough and have spare time) to make a step by step video guide. 

I have managed to follow all the steps, but I am sure what QT is to get this open.

Alternatively, if anyone is happy to assist me installing this, I will be glad to include them on my Phd( Use of Augmented Reality to HoloLens equipment to plan surgeries).

Again, thank you for reading this.

**Comment by eidelen** [comment]
Hi,
Would you like to build Dicom2Mesh with the GUI? If so I have to warn you, that this is very expermiental. If you want to use just the command line tool, QT is actually not required. Where exactly did you get stuck?

**Comment by eidelen** [comment]
Hi, I close that issue, as you didn't respond. Feel free to open it again.
Best regards,
Adrian
