### ISSUE TITLE
Installation error via Docker on mac

### ISSUE THREAD

**Issue by TZsong** [eidelen/DicomToMesh#51]
Hello guys, I had a problem when installing DicomToMesh using docker: `Unable to locate package dicom2mes`

**Comment by TZsong** [comment]
Unfortunately, using add-apt-repository-y directly on the Dockerfile doesn't seem to solve the problem. I did not use the provided Dockerfile, I just went directly to the ubuntu image and followed the steps to compile manually

**Comment by TZsong** [comment]
I ran into the same problem by going directly to the ubuntu image and following the steps to compile manually.

**Comment by TZsong** [comment]
I fixed the problem after specifying the dockerfile introduced in Ubuntu as the amd64 platform, thanks

**Comment by eidelen** [comment]
Hi,
I created the ppa package only for Ubunutu 18.04. I'm using the latest Sonoma version and the build process (cmake) works from scratch.
You write "I fixed the problem after specifying the dockerfile introduced in Ubuntu as the amd64 platform, thanks": Is there anything we can enhance / fix in our docker file? If so, I would be very glad if you can create a pull request and I take it into the main branch.
Thx,
Adrian

**Comment by rtuszik** [comment]
The Dockerfile is fine. However, your PPA only provides amd64 packages, so builds will fail for arm64. To ensure the build doesn’t default to arm64 on Apple silicon, the command should be:

```sh
docker build --platform linux/amd64 -t dicom2mesh docker
```

**Comment by TZsong** [comment]
> Hi, I created the ppa package only for Ubunutu 18.04. I'm using the latest Sonoma version and the build process (cmake) works from scratch. You write "I fixed the problem after specifying the dockerfile introduced in Ubuntu as the amd64 platform, thanks": Is there anything we can enhance / fix in our docker file? If so, I would be very glad if you can create a pull request and I take it into the main branch. Thx, Adrian

Hi,
I think the command to run on an arm64 machine should be
`docker build --platform linux/amd64 -t dicom2mesh docker`
Or you can adjust your dockerfile
`from --platform=linux/amd64 ubuntu:18.04`

Then add the `--platform amd64` argument to the `docker run` command as well,
`docker run --platform linux/amd64 -v /dicom/files/:/data dicom2mesh -i /data  -o /data/example.stl`
