### ISSUE TITLE
Folder with dicom can't be loaded.

### ISSUE THREAD

**Issue by Sir0ga90** [eidelen/DicomToMesh#52]
Folder with dicom can't be loaded.
Easy fix - 
dicomRoutines.cpp, line 68 `!` need to be added before `checkDataLoaded(rawVolumeData)`

**Comment by luzpaz** [comment]
make a PR perhaps ?

**Comment by Sir0ga90** [comment]
Permission is denied.

**Comment by eidelen** [comment]
@Sir0ga90 Everybody is allowed to make a pull request. Check this link: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by luzpaz** [comment]
@Sir0ga90 do you still plan to make a PR ?

**Comment by Sir0ga90** [comment]
@luzpaz 
as I have mentioned before access is denied
![image](https://github.com/user-attachments/assets/2252651a-253f-4d0e-90f3-bb700f0c31c2)

**Comment by luzpaz** [comment]
@Sir0ga90 you're misunderstanding git, I think. You need to set upstream to your fork of this repo; push changes to your fork and then make a PR from your fork against upstream https://github.com/eidelen/DicomToMesh

**Comment by Sir0ga90** [comment]
@luzpaz you'r misunderstanding what I have done. Upstream to the repo can't be created because of access rights to your repo.

**Comment by Sir0ga90** [comment]
@luzpaz, aha, forking has different workflow in compare with branches approach. Created pull request.
Thank you.
