### ISSUE TITLE
mesh reduction is too slow

### ISSUE THREAD

**Issue by hws203** [eidelen/DicomToMesh#54]
@eidelen Do you have any plan to speed up the mesh reduction function?  It looks to slow for my case which any some large voxels(more than 1GB float).

**Comment by hws203** [comment]
Maybe I meed to recompile the vtk with some other option for faster spped.

**Comment by eidelen** [comment]
Hi,
Just to be on the same page. The mesh reduction does not process voxel but an initial mesh. Here is the pipeline:
DICOM (Voxel) -> vtkMarchingCubes (3D Mesh) -> vtkQuadricDecimation (3D Mesh)
So, the vtkQuadricDecimation is the working horse which performs the reduction. I do not know the specifics of this reduction algorithms... that's for people without children :) If I would be in your shoes, I would export a non-reduced mesh. Then open it in MeshLab and check if you find a significantly faster decimation method. If you find something and it is in VTK, let me know.
This project might be also interesting for you: https://github.com/pyvista/fast-simplification
Enjoy the weekend

**Comment by hws203** [comment]
Yes, as you say, it is related to vtk library function. I change the vtkQuadricDecimation to vtkDecimatePro class, then it looks to work well until the end of poly data.  When I use vtkQuadricDecimation class, which does not work to the end of poly data. And I changed the DeepCopy to ShallowCopy in your vtrkRoutines too.
